# fly.toml app configuration file generated for yks-asistani-broken-silence-8853 on 2025-06-18T10:14:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yks-asistani-broken-silence-8853"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[mounts]
  source = "yks_data"
  destination = "/data"
